
[[language]]
language-servers = []
name = "julia"

[[grammar]]
name = "julia"
source = { git = "https://github.com/tree-sitter/tree-sitter-julia", rev = "e0f9dcd180fdcfcfa8d79a3531e11d99e79321d3" }

[[language]]
indent = { tab-width = 4, unit = "    " }
name = "markdown"

[[language]]
name = "rust"
rulers = []
text-width = 1000

[[language]]
indent = { tab-width = 4, unit = "    " }
name = "toml"

[[language]]
indent = { tab-width = 4, unit = "    " }
name = "typst"
